import enum


class TypeEvenementCommune(enum.Enum):
    CHANGEMENT_DE_NOM = 10
    CREATION = 20
    RETABLISSEMENT = 21
    SUPPRESSION = 30
    FUSION_SIMPLE = 31
    CREATION_COMMUNE_NOUVELLE = 32
    FUSION_ASSOCIATION = 33
    TRANSFORMATION_FUSION_ASSOCIATION_EN_FUSION_SIMPLE = 34
    SUPPRESSION_COMMUNE_DELEGUEE = 35
    CHANGEMENT_DÉPARTEMENT = 41
    TRANSFERT_CHEF_LIEU = 50
    TRANSFORMATION_COMMUNE_ASSOCIEE_EN_DELEGUEE = 70
    RETABLISSEMENT_COMMUNE_DELEGUEE = 71
