params:
  - params.yaml

vars:
  - src: "src"
  - raw: "data/01_raw"
  - clean: "data/02_clean"
  - main: "data/03_main"
  - python: PYTHONPATH=src python -m

stages:
  nettoyer-2020-municipales-1:
    cmd: >-
      sed '13751,13752s/ \t / / ; 16921s/ \t / /'
      < ${raw}/ministere_interieur/2020-municipales-1-bureau_de_vote_avant_correction.csv
      > ${raw}/ministere_interieur/2020-municipales-1-bureau_de_vote.csv
    deps:
      - ${raw}/ministere_interieur/2020-municipales-1-bureau_de_vote_avant_correction.csv
    outs:
      - ${raw}/ministere_interieur/2020-municipales-1-bureau_de_vote.csv

  normaliser-format-elections:
    foreach: ${scrutins}
    do:
      cmd: >-
        ${python} hexagonal.resultats.format_${item.format}
        ${raw}/ministere_interieur/${key}.csv ${clean}/elections/${key}.parquet ${item.encoding} "${item.delimiter}"
      deps:
        - ${raw}/ministere_interieur/${key}.csv
        - ${src}/hexagonal/resultats/format_${item.format}.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/elections/${key}.parquet

  candidats-nettoyer:
    foreach:
      2022-legislatives-1-candidats:
        delimiter: "\t"
        encoding: latin1
      2022-legislatives-2-candidats:
        delimiter: "\t"
        encoding: latin1
      2024-legislatives-1-candidats:
        delimiter: ";"
      2024-legislatives-2-candidats:
        delimiter: ";"
    do:
      cmd: >-
        ${python} hexagonal.candidatures.nettoyer
        ${item}
        "${raw}/ministere_interieur/${key}.csv"
        "${clean}/elections/${key}.csv"
      deps:
        - ${raw}/ministere_interieur/${key}.csv
        - ${src}/hexagonal/candidatures/nettoyer.py
      outs:
        - ${clean}/elections/${key}.csv

  2024-legislatives-candidats:
    foreach:
      - 1
      - 2
    do:
      cmd: >-
        ${python} hexagonal.candidatures.legislatives2024
        ${clean}/elections/2024-legislatives-${item}-candidats.csv
        ${raw}/lafranceinsoumise/2024-legislatives-nfp-sensibilites.csv
        ${raw}/lafranceinsoumise/2024-legislatives-nuances.csv
        ${raw}/lafranceinsoumise/2024-legislatives-candidats.csv
        ${main}/elections/2024-legislatives-${item}-candidats.csv
      deps:
        - ${clean}/elections/2024-legislatives-${item}-candidats.csv
        - ${raw}/lafranceinsoumise/2024-legislatives-nfp-sensibilites.csv
        - ${raw}/lafranceinsoumise/2024-legislatives-nuances.csv
        - ${raw}/lafranceinsoumise/2024-legislatives-candidats.csv
        - ${src}/hexagonal/candidatures/legislatives2024.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${main}/elections/2024-legislatives-${item}-candidats.csv

  2022-legislatives-candidats:
    foreach:
      - 1
      - 2
    do:
      cmd: >-
        ${python} hexagonal.candidatures.legislatives2022
        ${clean}/elections/2022-legislatives-${item}-candidats.csv
        ${raw}/le_monde/2022-legislatives-nuances.csv
        ${raw}/legis_2022/2022-legislatives-nuances.csv
        ${main}/elections/2022-legislatives-${item}-candidats.csv
      deps:
        - ${clean}/elections/2022-legislatives-${item}-candidats.csv
        - ${clean}/elections/2022-legislatives-1-circonscription.parquet
        - ${clean}/elections/2022-legislatives-2-circonscription.parquet
        - ${raw}/le_monde/2022-legislatives-nuances.csv
        - ${raw}/legis_2022/2022-legislatives-nuances.csv
        - ${src}/hexagonal/candidatures/legislatives2022.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${main}/elections/2022-legislatives-${item}-candidats.csv

  parrainages_nettoyer:
    foreach:
      - 2022
    do:
      deps:
        - ${raw}/conseil_constitutionnel/${item}-presidentielle-parrainages.csv
        - ${src}/hexagonal/parrainages/nettoyer.py
      outs:
        - ${clean}/elections/${item}-presidentielle-parrainages.csv
      cmd: >-
        ${python} hexagonal.parrainages.nettoyer
        ${raw}/conseil_constitutionnel/${item}-presidentielle-parrainages.csv
        ${clean}/elections/${item}-presidentielle-parrainages.csv

  parrainages_qualifier:
    foreach:
      - 2022
    do:
      deps:
        - ${clean}/elections/${item}-presidentielle-parrainages.csv
        - ${clean}/cog/departements.csv
        - ${clean}/cog/communes.csv
        - ${clean}/cog/communes_com.csv
        - ${src}/hexagonal/parrainages/qualifier.py
      outs:
        - ${main}/elections/${item}-presidentielle-parrainages.csv
      cmd: >-
        ${python} hexagonal.parrainages.qualifier
        ${clean}/elections/${item}-presidentielle-parrainages.csv
        ${clean}/cog/
        ${main}/elections/${item}-presidentielle-parrainages.csv

  correspondances_bureau_de_vote_circonscription:
    foreach:
      - 2024
    do:
      cmd: >-
        ${python} hexagonal.correspondances_circonscription
        ${clean}/elections/${item}-legislatives-1-bureau_de_vote.parquet
        ${clean}/elections/${item}-legislatives-1-candidats.csv
        ${clean}/elections/${item}-legislatives-correspondances-bureau_de_vote-circonscription.csv
      deps:
        - ${clean}/elections/${item}-legislatives-1-bureau_de_vote.parquet
        - ${clean}/elections/${item}-legislatives-1-candidats.csv
        - ${src}/hexagonal/correspondances_circonscription.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/elections/${item}-legislatives-correspondances-bureau_de_vote-circonscription.csv

  assemblee_nationale_fiches:
    deps:
      - ${raw}/assemblee-nationale.zip
      - ${src}/hexagonal/assemblee_nationale/fiches.py
      - ${src}/hexagonal/assemblee_nationale/utils.py
    outs:
      - ${clean}/assemblee_nationale/fiches.csv
      - ${clean}/assemblee_nationale/adresses_postales.csv
      - ${clean}/assemblee_nationale/adresses_electroniques.csv
    cmd: >-
      ${python} hexagonal.assemblee_nationale.fiches
      ${raw}/assemblee-nationale.zip
      ${clean}/assemblee_nationale/fiches.csv
      ${clean}/assemblee_nationale/adresses_postales.csv
      ${clean}/assemblee_nationale/adresses_electroniques.csv

  assemblee_nationale_mandats:
    deps:
      - ${raw}/assemblee-nationale.zip
      - ${src}/hexagonal/assemblee_nationale/mandats.py
      - ${src}/hexagonal/assemblee_nationale/utils.py
    outs:
      - ${clean}/assemblee_nationale/mandats.csv
    cmd: >-
      ${python} hexagonal.assemblee_nationale.mandats
      ${raw}/assemblee-nationale.zip
      ${clean}/assemblee_nationale/mandats.csv

  assemblee_nationale_groupes:
    deps:
      - ${raw}/assemblee-nationale.zip
      - ${src}/hexagonal/assemblee_nationale/groupes.py
      - ${src}/hexagonal/assemblee_nationale/utils.py
    outs:
      - ${clean}/assemblee_nationale/groupes.csv
      - ${clean}/assemblee_nationale/affiliations.csv
    cmd: >-
      ${python} hexagonal.assemblee_nationale.groupes
      ${raw}/assemblee-nationale.zip
      ${clean}/assemblee_nationale/groupes.csv
      ${clean}/assemblee_nationale/affiliations.csv

  assemblee_nationale_commissions:
    deps:
      - ${raw}/assemblee-nationale.zip
      - ${src}/hexagonal/assemblee_nationale/commissions.py
      - ${src}/hexagonal/assemblee_nationale/utils.py
    outs:
      - ${clean}/assemblee_nationale/commissions.csv
    cmd: >-
      ${python} hexagonal.assemblee_nationale.commissions
      ${raw}/assemblee-nationale.zip
      ${clean}/assemblee_nationale/commissions.csv

  assemblee_nationale_deputes:
    deps:
      - ${src}/hexagonal/assemblee_nationale/deputes.py
      - ${clean}/assemblee_nationale/fiches.csv
      - ${clean}/assemblee_nationale/adresses_electroniques.csv
      - ${clean}/assemblee_nationale/commissions.csv
      - ${clean}/assemblee_nationale/mandats.csv
      - ${clean}/assemblee_nationale/affiliations.csv
    outs:
      - ${main}/assemblee_nationale/deputes.csv
    cmd:
      ${python} hexagonal.assemblee_nationale.deputes
      ${clean}/assemblee_nationale
      ${main}/assemblee_nationale/deputes.csv

  rne_nettoyer:
    foreach:
      - conseillers_arrondissement
      - conseillers_municipaux
      - conseillers_departementaux
      - conseillers_regionaux
      - conseillers_csp
    do:
      deps:
        - ${raw}/rne/${item}.csv
        - ${src}/hexagonal/rne/extraire.py
      outs:
        - ${clean}/rne/${item}.csv
      cmd: >-
        ${python} hexagonal.rne.extraire
        ${raw}/rne
        ${clean}/rne
        ${item}

  annuaire_extraire:
    deps:
      - ${raw}/annuaire/annuaire.tar.bz2
      - ${src}/hexagonal/annuaire/extraire_organismes.py
    outs:
      - ${raw}/annuaire/mairies.json
      - ${raw}/annuaire/epcis.json
      - ${raw}/annuaire/conseils_departementaux.json
      - ${raw}/annuaire/conseils_regionaux.json
      - ${raw}/annuaire/prefectures.json
    cmd: >-
      ${python} hexagonal.annuaire.extraire_organismes
      ${raw}/annuaire/annuaire.tar.bz2
      ${raw}/annuaire/

  annuaires_nettoyer:
    deps:
      - ${raw}/annuaire/mairies.json
      - ${raw}/annuaire/conseils_departementaux.json
      - ${src}/hexagonal/annuaire/nettoyer.py
    outs:
      - ${clean}/annuaire/mairies.csv
      - ${clean}/annuaire/conseils_departementaux.csv
    cmd: >-
      ${python} hexagonal.annuaire.nettoyer
      ${raw}/annuaire
      ${clean}/annuaire
      
  cog_nettoyer:
    deps:
      - ${raw}/insee/cog.zip
      - ${src}/hexagonal/cog/extraire.py
    outs:
      - ${clean}/cog/regions.csv
      - ${clean}/cog/departements.csv
      - ${clean}/cog/cantons.csv
      - ${clean}/cog/communes.csv
      - ${clean}/cog/communes_com.csv
      - ${clean}/cog/communes_historiques.csv
      - ${clean}/cog/com.csv
      - ${clean}/cog/ctcd.csv
      - ${clean}/cog/mouvements_communes.csv
    cmd: >-
      ${python} hexagonal.cog.extraire
      ${raw}/insee/cog.zip
      ${clean}/cog

  epci_nettoyer:
    deps:
      - ${raw}/epci.xlsx
      - ${src}/hexagonal/intercommunalite/nettoyer.py
    outs:
      - ${clean}/epci.csv
      - ${clean}/communes_epci.csv
    cmd: >-
      ${python} hexagonal.intercommunalite.nettoyer
      ${raw}/epci.xlsx
      ${clean}/epci.csv
      ${clean}/communes_epci.csv

  admin_express_extraire:
    deps:
      - ${raw}/ign/admin_express/admin_express_cog.7z
      - ${src}/hexagonal/admin_express/extraire.py
    outs:
      - ${raw}/ign/admin_express/communes.cpg
      - ${raw}/ign/admin_express/communes.dbf
      - ${raw}/ign/admin_express/communes.prj
      - ${raw}/ign/admin_express/communes.shp
      - ${raw}/ign/admin_express/communes.shx
      - ${raw}/ign/admin_express/communes_deleguees.cpg
      - ${raw}/ign/admin_express/communes_deleguees.dbf
      - ${raw}/ign/admin_express/communes_deleguees.prj
      - ${raw}/ign/admin_express/communes_deleguees.shp
      - ${raw}/ign/admin_express/communes_deleguees.shx
      - ${raw}/ign/admin_express/arrondissements_municipaux.cpg
      - ${raw}/ign/admin_express/arrondissements_municipaux.dbf
      - ${raw}/ign/admin_express/arrondissements_municipaux.prj
      - ${raw}/ign/admin_express/arrondissements_municipaux.shp
      - ${raw}/ign/admin_express/arrondissements_municipaux.shx
    cmd: >-
      ${python} hexagonal.admin_express.extraire
      ${raw}/ign/admin_express/admin_express_cog.7z
      ${raw}/ign/admin_express/

  population_nettoyer:
    deps:
      - ${raw}/insee/population_municipale.xlsx
      - ${src}/hexagonal/population/nettoyer.py
    outs:
      - ${clean}/population_municipale.csv
    cmd: >-
      ${python} hexagonal.population.nettoyer
      ${raw}/insee/population_municipale.xlsx
      ${clean}/population_municipale.csv

  cog_qualifier:
    foreach:
      - communes
    do:
      deps:
        - ${clean}/cog/${item}.csv
        - ${clean}/population_municipale.csv
        - ${clean}/epci.csv
        - ${clean}/communes_epci.csv
        - ${src}/hexagonal/cog/qualifier_communes.py
      outs:
        - ${main}/cog/${item}.csv
      cmd: >-
        ${python} hexagonal.cog.qualifier_communes
        ${clean}/cog/${item}.csv
        ${clean}/population_municipale.csv
        ${clean}/epci.csv
        ${clean}/communes_epci.csv
        ${main}/cog/${item}.csv

  communes_details:
    deps:
      - ${src}/scripts/geodata/communes.sh
      - ${raw}/ign/admin_express/communes.cpg
      - ${raw}/ign/admin_express/communes.dbf
      - ${raw}/ign/admin_express/communes.prj
      - ${raw}/ign/admin_express/communes.shp
      - ${raw}/ign/admin_express/communes.shx
    outs:
      - ${main}/geodata/communes.json
    cmd: >-
      ${src}/scripts/geodata/communes.sh
      ${raw}/ign/admin_express/communes.shp
      ${main}/geodata/communes.json

  circonscriptions_details:
    deps:
      - ${raw}/insee/insee_circonscriptions_legislatives.zip
      - ${src}/scripts/geodata/circonscriptions.sh
    outs:
      - ${main}/geodata/circonscriptions_legislatives.json
    cmd: >-
      ${src}/scripts/geodata/circonscriptions.sh
      ${raw}/insee/insee_circonscriptions_legislatives.zip
      ${main}/geodata/circonscriptions_legislatives.json

  communes_carto:
    foreach: ${zones_carto}
    do:
      deps:
        - ${src}/scripts/cartographie/filter_project.sh
        - ${main}/geodata/communes.json
      outs:
        - ${main}/cartographie/communes_${key}.json
      cmd: >-
        ${src}/scripts/cartographie/filter_project.sh
        ${main}/geodata/communes.json
        ${main}/cartographie/communes_${key}.json
        ${key}
        '${item.filtre}'
        ${item.projection}

  circonscriptions_carto:
    foreach: ${zones_carto}
    do:
      deps:
        - ${src}/scripts/cartographie/filter_project.sh
        - ${main}/geodata/circonscriptions_legislatives.json
      outs:
        - ${main}/cartographie/circonscriptions_${key}.json
      cmd: >-
        ${src}/scripts/cartographie/filter_project.sh
        ${main}/geodata/circonscriptions_legislatives.json
        ${main}/cartographie/circonscriptions_${key}.json
        ${key}
        '${item.filtre}'
        ${item.projection}

  paris_carto:
    deps:
      - ${raw}/paris/2022-secteur-bureaux.json
      - ${raw}/paris/2024-secteur-bureaux.json
    outs:
      - ${main}/cartographie/paris-2022-2024.json
    cmd: >-
      mapshaper
      -i ${raw}/paris/2022-secteur-bureaux.json ${raw}/paris/2024-secteur-bureaux.json combine-files
      -proj EPSG:3857 'target=*'
      -clean snap-interval=10m 'target=*'
      -rename-layers 2022,2024 target=2022-secteur-bureaux,2024-secteur-bureaux
      -o ${main}/cartographie/paris-2022-2024.json format=topojson 'target=*'

  extraire_geonames_cities1000:
    deps:
      - ${raw}/geonames/cities1000.zip
      - ${src}/hexagonal/geonames/extract.py
    outs:
      - ${clean}/geonames/cities1000.json.zst
    cmd: ${python} hexagonal.geonames.extract ${raw}/geonames/cities1000.zip ${clean}/geonames/cities1000.json.zst

  pays_carto:
    deps:
      - ${src}/scripts/cartographie/pays.sh
      - ${raw}/natural_earth/ne_10m_admin_0_countries.zip
      - ${clean}/geonames/cities1000.json.zst
    outs:
      - ${main}/cartographie/pays.json.zst
    cmd: >-
      ${src}/scripts/cartographie/pays.sh
      ${raw}/natural_earth/ne_10m_admin_0_countries.zip
      ${clean}/geonames/cities1000.json.zst
      ${main}/cartographie/pays.json.zst

  extraire_codes_postaux:
    deps:
      - ${raw}/la_poste/base_officielle_codes_postaux.csv
      - ${src}/hexagonal/codes_postaux/extraire.py
    outs:
      - ${clean}/codes_postaux.csv
    cmd: >-
      ${python} hexagonal.codes_postaux.extraire
      ${raw}/la_poste/base_officielle_codes_postaux.csv
      ${clean}/codes_postaux.csv

  qualifier_codes_postaux:
    deps:
      - ${clean}/codes_postaux.csv
      - ${main}/cog/communes.csv
      - ${src}/hexagonal/codes_postaux/qualifier.py
    outs:
      - ${main}/codes_postaux.csv
    cmd: >-
      ${python} hexagonal.codes_postaux.qualifier
      ${clean}/codes_postaux.csv
      ${main}/cog/communes.csv
      ${main}/codes_postaux.csv

  extraire_contours_iris:
    deps:
      - ${raw}/ign/iris-metropole.7z
    outs:
      - ${raw}/ign/iris-metropole.gpkg
    cmd: >-
      7z e ${raw}/ign/iris-metropole.7z -so -r "iris.gpkg" > "${raw}/ign/iris-metropole.gpkg"

  extraire_filosofi_disponible:
    deps:
      - ${raw}/insee/filosofi-disponible.zip
      - ${src}/hexagonal/filosofi/extraire.py
    outs:
      - ${clean}/filosofi/disponible.csv
    cmd: >-
      ${python} hexagonal.filosofi.extraire
      ${raw}/insee/filosofi-disponible.zip
      ${clean}/filosofi/disponible.csv
