params:
- params.yaml

vars:
- raw: "data/01_raw"
- clean: "data/02_clean"
- main: "data/03_main"

stages:
  raw:
    foreach: ${scrutins}
    do:
      cmd: >-
        mkdir -p ${raw} && curl ${item.url} -o ${raw}/${key}.csv --progress-bar --location
      outs:
      - ${raw}/${key}.csv

  clean:
    foreach: ${scrutins}
    do:
      cmd: >-
        mkdir -p ${clean} && python -m src.backend.resultats.format_${item.format} ${raw}/${key}.csv ${clean}/${key}.csv ${item.encoding} ${item.delimiter}
      deps:
      - ${raw}/${key}.csv
      - src/backend/resultats/format_${item.format}.py
      outs:
      - ${clean}/${key}.csv
