params:
- params.yaml

vars:
- src: "src/"
- raw: "data/01_raw"
- clean: "data/02_clean"
- main: "data/03_main"

stages:
  nettoyer-2020-municipales-1:
    cmd: >-
      sed '13751,13752s/ \t / / ; 16921s/ \t / /'
      < ${raw}/2020-municipales-1-bureau_de_vote_avant_correction.csv
      > ${raw}/2020-municipales-1-bureau_de_vote.csv
    deps:
      - ${raw}/2020-municipales-1-bureau_de_vote_avant_correction.csv
    outs:
      - ${raw}/2020-municipales-1-bureau_de_vote.csv
  clean:
    foreach: ${scrutins}
    do:
      cmd: >-
        PYTHONPATH=${src}
        python -m hexagonal.resultats.format_${item.format}
        ${raw}/${key}.csv ${clean}/${key}.csv ${item.encoding} "${item.delimiter}"
      deps:
      - ${raw}/${key}.csv
      - src/backend/resultats/format_${item.format}.py
      outs:
      - ${clean}/${key}.csv
