params:
  - params.yaml

vars:
  - src: "src"
  - raw: "data/01_raw"
  - clean: "data/02_clean"
  - main: "data/03_main"

stages:
  nettoyer-2020-municipales-1:
    cmd: >-
      sed '13751,13752s/ \t / / ; 16921s/ \t / /'
      < ${raw}/2020-municipales-1-bureau_de_vote_avant_correction.csv
      > ${raw}/2020-municipales-1-bureau_de_vote.csv
    deps:
      - ${raw}/2020-municipales-1-bureau_de_vote_avant_correction.csv
    outs:
      - ${raw}/2020-municipales-1-bureau_de_vote.csv

  clean:
    foreach: ${scrutins}
    do:
      cmd: >-
        PYTHONPATH=${src}
        python -m hexagonal.resultats.format_${item.format}
        ${raw}/${key}.csv ${clean}/${key}.csv ${item.encoding} "${item.delimiter}"
      deps:
        - ${raw}/${key}.csv
        - ${src}/hexagonal/resultats/format_${item.format}.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/${key}.csv

  2024-legislatives-candidats:
    foreach:
      - 1
      - 2
    do:
      cmd: >-
        PYTHONPATH=${src}
        python -m hexagonal.candidatures.2024_legislatives
        ${raw}/2024-legislatives-${item}-candidats.csv
        ${raw}/2024-legislatives-nfp-sensibilites.csv
        ${raw}/2024-legislatives-nuances-lfi.csv
        ${clean}/2024-legislatives-${item}-candidats.csv
      deps:
        - ${raw}/2024-legislatives-${item}-candidats.csv
        - ${raw}/2024-legislatives-nfp-sensibilites.csv
        - ${raw}/2024-legislatives-nuances-lfi.csv
        - ${src}/hexagonal/candidatures/2024_legislatives.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/2024-legislatives-${item}-candidats.csv


  2022-legislatives-candidats:
    foreach:
      - 1
      - 2
    do:
      cmd: >-
        PYTHONPATH=${src}
        python -m hexagonal.candidatures.2022_legislatives
        ${raw}/2022-legislatives-${item}-candidats.csv
        ${raw}/2022-legislatives-nuances-lemonde.csv
        ${raw}/2022-legislatives-nuances-legis-2022.csv
        ${clean}/2022-legislatives-${item}-candidats.csv
      deps:
        - ${raw}/2022-legislatives-${item}-candidats.csv
        - ${raw}/2022-legislatives-nuances-lemonde.csv
        - ${raw}/2022-legislatives-nuances-legis-2022.csv
        - ${src}/hexagonal/candidatures/2022_legislatives.py
        - ${src}/hexagonal/codes.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/2022-legislatives-${item}-candidats.csv

  correspondances_bureau_de_vote_circonscription:
    foreach:
      - 2024
    do:
      cmd: >-
        PYTHONPATH=${src}
        python -m  hexagonal.correspondances_circonscription
        ${clean}/${item}-legislatives-1-bureau_de_vote.csv
        ${clean}/${item}-legislatives-1-candidats.csv
        ${clean}/${item}-legislatives-correspondances-bureau_de_vote-circonscription.csv
      deps:
        - ${clean}/${item}-legislatives-1-bureau_de_vote.csv
        - ${clean}/${item}-legislatives-1-candidats.csv
        - ${src}/hexagonal/correspondances_circonscription.py
        - ${src}/hexagonal/codes.py
      outs:
        - ${clean}/${item}-legislatives-correspondances-bureau_de_vote-circonscription.csv
