scrutins:
  2012-presidentielle-bureau_de_vote:
    encoding: latin1
    format: 2014
    delimiter: ";"
  2014-europeenne-bureau_de_vote:
    encoding: latin1
    format: 2014
    delimiter: ";"
  2017-legislatives-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2017-legislatives-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2017-presidentielle-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2017-presidentielle-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2019-europeenne-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2020-municipales-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: "	"
  2020-municipales-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2021-departementales-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2021-departementales-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2021-regionales-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2021-regionales-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-presidentielle-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-presidentielle-1-circonscription:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-presidentielle-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-presidentielle-2-circonscription:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-legislatives-1-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-legislatives-1-circonscription:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-legislatives-2-bureau_de_vote:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2022-legislatives-2-circonscription:
    encoding: latin1
    format: 2017
    delimiter: ";"
  2024-europeenne-bureau_de_vote:
    encoding: utf8
    format: 2017
    delimiter: ";"
  2024-europeenne-circonscription:
    encoding: utf8
    format: 2017
    delimiter: ";"
  2024-legislatives-1-bureau_de_vote:
    encoding: utf8
    format: 2017
    delimiter: ";"
  2024-legislatives-1-circonscription:
    encoding: utf8
    format: 2017
    delimiter: ";"
  2024-legislatives-2-bureau_de_vote:
    encoding: utf8
    format: 2017
    delimiter: ";"
  2024-legislatives-2-circonscription:
    encoding: utf8
    format: 2017
    delimiter: ";"

zones_carto:
  hexagone:
    projection: EPSG:2154
    filtre: code_departement.length === 2
  guadeloupe:
    projection: EPSG:5490
    filtre: code_departement === "971"
  martinique:
    projection: EPSG:5490
    filtre: code_departement === "972"
  guyane:
    projection: EPSG:2972
    filtre: code_departement === "973"
  reunion:
    projection: EPSG:2975
    filtre: code_departement === "974"
  mayotte:
    projection: EPSG:4471
    filtre: code_departement === "976"
