scrutins:
  2012-presidentielle:
    encoding: latin1
  2017-presidentielle-1:
    encoding: latin1
  2017-presidentielle-2:
    encoding: latin1
  2022-presidentielle-1:
    encoding: latin1
  2022-presidentielle-2:
    encoding: latin1
  2017-legislatives-1:
    encoding: latin1
  2017-legislatives-2:
    encoding: latin1
  2022-legislatives-1:
    encoding: latin1
  2022-legislatives-2:
    encoding: latin1
  2024-legislatives-1:
    encoding: utf8
  2024-legislatives-2:
    encoding: utf8
  2014-europeenne:
    encoding: latin1
  2019-europeenne:
    encoding: latin1
  2024-europeenne:
    encoding: utf8
  2020-municipales-1:
    encoding: latin1
  2020-municipales-2:
    encoding: latin1
  2021-regionales-1:
    encoding: latin1
  2021-regionales-2:
    encoding: latin1
  2021-departementales-1:
    encoding: latin1
  2021-departementales-2:
    encoding: latin1
  2005-referendum:
    encoding: latin1
