scrutins:
  2012-presidentielle:
    url: https://www.data.gouv.fr/fr/datasets/r/206b1668-2b31-46da-b957-9857f94fe85c
    encoding: latin1
  2017-presidentielle-1:
    url: https://www.data.gouv.fr/fr/datasets/r/8fdb0926-ea9d-4fb4-a136-7767cd97e30b
    encoding: latin1
  2017-presidentielle-2:
    url: https://www.data.gouv.fr/fr/datasets/r/2e3e44de-e584-4aa2-8148-670daf5617e1
    encoding: latin1
  2022-presidentielle-1:
    url: https://www.data.gouv.fr/fr/datasets/r/79b5cac4-4957-486b-bbda-322d80868224
    encoding: latin1
  2022-presidentielle-2:
    url: https://www.data.gouv.fr/fr/datasets/r/4dfd05a9-094e-4043-8a19-43b6b6bbe086
    encoding: latin1
  2017-legislatives-1:
    url: https://www.data.gouv.fr/fr/datasets/r/80cb1309-9147-4bae-b6e2-79877d549b50
    encoding: latin1
  2017-legislatives-2:
    url: https://www.data.gouv.fr/fr/datasets/r/8eb61f3e-dfdf-496e-85af-2859cd7383c3
    encoding: latin1
  2022-legislatives-1:
    url: https://www.data.gouv.fr/fr/datasets/r/a1f73b85-8194-44f4-a2b7-c343edb47d32
    encoding: latin1
  2022-legislatives-2:
    url: https://www.data.gouv.fr/fr/datasets/r/cada247a-6528-44e7-8308-30c0c335a4b2
    encoding: latin1
  2024-legislatives-1:
    url: https://www.data.gouv.fr/fr/datasets/r/6813fb28-7ec0-42ff-a528-2bc3d82d7dcd
    encoding: latin1
  2024-legislatives-2:
    url: https://www.data.gouv.fr/fr/datasets/r/ca974f04-cfd9-4da8-8554-4a868a09c6c2
    encoding: latin1
  2014-europeenne:
    url: https://www.data.gouv.fr/fr/datasets/r/c5af18ce-b673-4019-a9c3-07ee6209668c
    encoding: latin1
  2019-europeenne:
    url: https://www.data.gouv.fr/fr/datasets/r/77c4450b-7fa7-425c-84da-4f7bf4b97820
    encoding: latin1
  2024-europeenne:
    url: https://www.data.gouv.fr/fr/datasets/r/cc1883d9-1265-4365-b754-fb6aef22d82e
    encoding: latin1
  2020-municipales-1:
    url: https://www.data.gouv.fr/fr/datasets/r/248f6f21-68ad-45f3-82f5-53fffabce5f3
    encoding: latin1
  2020-municipales-2:
    url: https://www.data.gouv.fr/fr/datasets/r/7e641d2e-e017-43d4-9434-49d5acd44b4b
    encoding: latin1
  2021-regionales-1:
    url: https://www.data.gouv.fr/fr/datasets/r/52c3e6f1-2faa-4295-9f76-5b0e9cb9f7b0
    encoding: latin1
  2021-regionales-2:
    url: https://www.data.gouv.fr/fr/datasets/r/75221ab0-2066-4a11-bc42-b0f76d201dfe
    encoding: latin1
  2021-departementales-1:
    url: https://www.data.gouv.fr/fr/datasets/r/57370a9b-7fa1-465c-a051-c984fc21321f
    encoding: latin1
  2021-departementales-2:
    url: https://www.data.gouv.fr/fr/datasets/r/b34b36d9-e416-4144-8384-d101b140afaf
    encoding: latin1
  2005-referendum:
    url: https://www.data.gouv.fr/s/resources/referendum-de-2005-resultats-par-bureaux-de-vote/20150925-112918/RF05_BVot.ttx
    encoding: latin1
