scrutins:
#  2012-presidentielle:
#    encoding: latin1
#    format: 2014
  2017-presidentielle-1:
    encoding: latin1
    format: 2017
  2017-presidentielle-2:
    encoding: latin1
    format: 2017
  2022-presidentielle-1:
    encoding: latin1
    format: 2017
  2022-presidentielle-2:
    encoding: latin1
    format: 2017
  2017-legislatives-1:
    encoding: latin1
    format: 2017
  2017-legislatives-2:
    encoding: latin1
    format: 2017
  2022-legislatives-1:
    encoding: latin1
    format: 2017
  2022-legislatives-2:
    encoding: latin1
    format: 2017
  2024-legislatives-1:
    encoding: utf8
    format: 2017
  2024-legislatives-2:
    encoding: utf8
    format: 2017
#  2014-europeenne:
#    encoding: latin1
#    format: 2014
  2019-europeenne:
    encoding: latin1
    format: 2017
  2024-europeenne:
    encoding: utf8
    format: 2017
  2020-municipales-1:
    encoding: latin1
    format: 2017
  2020-municipales-2:
    encoding: latin1
    format: 2017
  2021-regionales-1:
    encoding: latin1
    format: 2017
  2021-regionales-2:
    encoding: latin1
    format: 2017
  2021-departementales-1:
    encoding: latin1
    format: 2017
  2021-departementales-2:
    encoding: latin1
    format: 2017
#  2005-referendum:
#    encoding: latin1
#    format: 2014
